//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analisis2Grupo9.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class analisis2_2022Entities : DbContext
    {
        public analisis2_2022Entities()
            : base("name=analisis2_2022Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria_Insumo> Categoria_Insumo { get; set; }
        public virtual DbSet<Categoria_Ticket> Categoria_Ticket { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Estado_Ticket> Estado_Ticket { get; set; }
        public virtual DbSet<Insumo> Insumo { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Requisicion_Interna> Requisicion_Interna { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Ticket_Seguimiento> Ticket_Seguimiento { get; set; }
    }
}
