//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analisis2Grupo9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisicion_Interna
    {
        public int id_requisicion { get; set; }
        public Nullable<int> id_ticket_seguimiento { get; set; }
        public Nullable<int> id_insumo { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
    
        public virtual Insumo Insumo { get; set; }
        public virtual Ticket_Seguimiento Ticket_Seguimiento { get; set; }
    }
}
