//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analisis2Grupo9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Ticket_Seguimiento = new HashSet<Ticket_Seguimiento>();
        }
    
        public int id_ticket { get; set; }
        public Nullable<int> id_empleado_solicitud { get; set; }
        public Nullable<int> id_empleado_asignacion { get; set; }
        public Nullable<int> id_categoria_ticket { get; set; }
        public Nullable<int> id_estado_ticket { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
    
        public virtual Categoria_Ticket Categoria_Ticket { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual Estado_Ticket Estado_Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Seguimiento> Ticket_Seguimiento { get; set; }
    }
}
